apiVersion: v1
spec:
  containers:
    - name: postgresql
      image: centos/postgresql
      env:
        - name: DB_NAME
          value: $db_name
        - name: DB_USER
          value: $db_user
        - name: DB_PASS
          value: $db_pass
      ports:
        - containerPort: 5432
metadata:
  name: postgresql
  labels:
    name: postgresql
kind: Pod
